Recipe = {
  prep: [
    {
      src: "gif",
      title: "Shiitake",
      direction:
        "Place them in a bowl of warm water (approximately 40° to 50°C/104° to 122°F) and allow them to soak for 10 minutes to rehydrate",
      amount: "1 oz",
      timer: 10,
      complete: false,
    },
    {
      src: "gif",
      title: "Seafood Mushroom",
      direction: [
        "Trim the ends off",
        "Cut mushrooms in half",
        "Place in a bowl of cold water to remove dirt",
      ],
      amount: "2 oz",
      timer: 10,
      complete: false,
    },
    {
      src: "gif",
      title: "King Oyster Mushroom",
      direction: [
        "slice at an angle into thin 1/4-inch thick pieces.",
        "Stack them together a few at a time and slice into thin 1/2-inch sticks",
      ],
      amount: "1 oz",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Chicken Breast",
      directions: [
        "Divide the chicken breast (12 oz) into two halves. If you look carefully, you can see that the grain of the protein is divided, with one half going up and down and the other half going left to right",
        "Starting with the bigger half, slice the breast into 1/4-inch pieces going along the grain. Then, just like with the vegetables and mushrooms, we’ll stack the chicken slices and cut them into 1/4-inch strips.",
        "You can use the same technique with the other half or try this one. Butterfly the remaining half of the chicken breast and slice each piece in half again holding your knife parallel to the cutting board. Then, stack the pieces together and cut them along the grain into 1/4-inch strips.",
      ],
      amount: "12 oz",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Carrot",
      direction:
        "Make a thin slice on one side of the carrot, then place it on the flat side. This creates a stable base and makes the carrot less likely to roll when cutting. Cut the carrot into 1/4-inch slices, then stack those slices and cut them into sticks. Set aside.",
      amount: "2 oz",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Scallion",
      direction: "cut the scallion into 2- to 3-inch pieces.",
      amount: "1 bunch",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Garlic",
      direction: "flatten with your knife, then roughly chop.",
      amount: "2 clove",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Red Onion",
      direction: "cut along the grain into 1/4-inch slices",
      amount: "2 oz",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Marinate Chicken",
      direction: [
        "Place the chicken in a bowl.",
        "Add the oyster sauce (1 tbsp)",
        "white pepper (0.25 tsp)",
        "chicken bouillon powder (0.50 tsp)",
        "cornstarch (1.5 tsp)",
        "and water (2 tbsp)",
        "Mix together and set aside.",
      ],
      amount: "",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Make Sauce",
      direction: [
        "In a separate bowl",
        "combine the oyster sauce (2 tbsp)",
        "light soy sauce (1 tbsp)",
        "sugar (1 tsp)",
        "salt",
        "chicken bouillon powder (1 tsp)",
        "Mix to combine",
      ],
      amount: "2 clove",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Cook Noodles",
      direction: [
        "Bring a large pot or wok of water to a boil. My dad like to use hot water to save cooking time.",
        "Once the water comes to a boil, add the noodle (18 oz), using your fingers to gently unravel them as you place them in. Using chopsticks, gently break apart the noodles until the water comes back to a boil.",
        "Lower the heat to medium and cook for another 8-10 minutes (total cook time after adding in the noodles should be about 10-15 minutes). You’ll know the noodles are cooked when you take a bite out of a noodle and there isn’t a stiff interior.",
        "Once cooked through, strain the noodles and rinse under cold water to stop the cooking process.",
      ],
      amount: "",
      timer: null,
      complete: false,
    },
    {
      src: "gif",
      title: "Cook Chicken",
      direction: [
        "Bring a pot of water to a boil.",
        "Once the water reaches a boil, lower the heat to medium. Add the marinated chicken.",
        "Cook for about 1-3 minutes, then strain and rinse briefly under cold water. Do not dispose of the cooking water just yet!",
        "Set aside 1 1/2 cups of cooking water to use for the sauce later.",
      ],
      amount: "",
      timer: [1, 2, 3],
      complete: false,
    },
    {
      src: "gif",
      title: "Stir fry ingredients",
      direction: [
        "In a wok, heat up the corn oil (1 tbsp).  (feel free to use any other high smoke point oil like peanut or vegetable oil.)",
        "Once hot, add in the shallot, garlic, and rehydrated shiitake mushroom and stir fry.",
        "After about 1-2 minutes (we'll tell you when), add in the seafood mushrooms, king oyster mushroom and red onion.",
        "After another 2 minutes (we'll tell you when), add the carrots.",
        "Make sure you're constantly moving and tossing the ingredients around.",
        "Stir fry for 1-2 minutes then add the cooking wine (1 tsp).",
        "Add the chicken and bean sprouts(4 oz)",
        "followed by the reserved 1 1/2 cup of chicken cooking water and scallions.",
        "Add the sauce and lower the heat to medium. Taste and adjust accordingly, adding more salt if needed.",
        "In a separate bowl, the remaining cornstarch (3 tsp) and water (1.5 tbsp) together to create slurry and add it to the stir fry. Mix over low heat to thicken.",
        "Lastly, add the sesame oil (1 tsp) and toss to combine.",
        "Place the noodles on a large platter and top with the chicken and vegetable stir fry. Toss everything together when ready to serve.",
      ],
      amount: "",
      timer: null,
      complete: false,
    },
  ],
};
